import argparse
import os
import sys
import time
from dotenv import load_dotenv

from github_client import GitHubClient
from agent import process_task
from git_manager import setup_worktree, cleanup_worktree, create_pull_request, post_pr_comment

# Load environment variables from .env file
load_dotenv()

# Valid trigger statuses from the plan
VALID_STATUSES = [
    "AI TODO",
    "AI FOLLOW UP QUESTIONS ANSWERED",
    "AI PLAN FEEDBACK",
    "AI READY TO IMPLEMENT",
    "AI PR REVIEW FEEDBACK"
]

LOCKED_STATUS = "AI WORKING"

def parse_arguments():
    parser = argparse.ArgumentParser(description="GitHub Agent Orchestrator")
    parser.add_argument(
        "--status",
        choices=VALID_STATUSES,
        help="The specific ticket status the orchestrator should look for to process once. If omitted, runs in continuous daemon mode."
    )
    parser.add_argument(
        "--repo-path",
        required=True,
        help="The local path to the target git repository."
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=60,
        help="Polling interval in seconds for daemon mode (default: 60)."
    )
    return parser.parse_args()

def check_environment_variables():
    token = os.getenv("GITHUB_TOKEN")
    project_id = os.getenv("GITHUB_PROJECT_ID")
    status_field_id = os.getenv("GITHUB_STATUS_FIELD_ID")

    if not all([token, project_id, status_field_id]):
        print("[!] Error: Missing required environment variables.", file=sys.stderr)
        print("[!] Ensure GITHUB_TOKEN, GITHUB_PROJECT_ID, and GITHUB_STATUS_FIELD_ID are set in .env", file=sys.stderr)
        sys.exit(1)
        
    return token, project_id, status_field_id

def print_agent_context(task):
    print("\n--- Agent Context ---")
    print(f"Title: {task['issue_title']}")
    print(f"Repo: {task['repo_name']}")
    print(f"Body Content:\n{task['issue_body']}")
    if task.get('issue_comments'):
        print(f"\nRecent Comments ({len(task['issue_comments'])}):")
        print("\n---\n".join(task['issue_comments']))
    print("---------------------\n")

def run_orchestration_loop(gh_client, task, target_status, repo_path):
    print(f"[*] Locking task by setting status to '{LOCKED_STATUS}'...")
    try:
        gh_client.update_item_status(task['project_item_id'], LOCKED_STATUS)
        print(f"[*] Task successfully locked.")
    except Exception as e:
        print(f"[!] Failed to update status to {LOCKED_STATUS}: {e}")
        sys.exit(1)

    print_agent_context(task)

    try:
        worktree_path = setup_worktree(repo_path, task['issue_number'])
    except Exception as e:
        print(f"[!] Failed to set up worktree. Aborting agent execution.")
        sys.exit(1)

    try:
        print(f"[*] Handing task over to Gemini CLI (cwd: {worktree_path})...")
        next_status, agent_comment = process_task(target_status, task, cwd=worktree_path)
    finally:
        cleanup_worktree(repo_path, worktree_path)
    
    # Automatically handle PR creation if the agent completed the implementation
    if next_status == "AI PR READY":
        if target_status == "AI PR REVIEW FEEDBACK":
            # For review feedback, the PR already exists, so we just post a comment to it
            post_pr_comment(repo_path, task['issue_number'], f"**🤖 Posted by Agent Orchestrator:**\n\n{agent_comment}")
        else:
            # For all other states (AI TODO, AI READY TO IMPLEMENT, etc.), create a new PR
            pr_url = create_pull_request(repo_path, task['issue_title'], task['issue_number'], pr_description=agent_comment)
            if pr_url:
                agent_comment += f"\n\n**Pull Request:** {pr_url}"
            else:
                agent_comment += "\n\n*(Failed to automatically generate Pull Request link. Please check the branch manually.)*"

    print(f"\n--- Agent Response ---")
    print(agent_comment)
    print(f"----------------------\n")
    
    print(f"[*] Agent determined the next status should be: '{next_status}'")
    
    if agent_comment:
        print(f"[*] Posting agent response as a comment on Issue #{task['issue_number']}...")
        
        # Add a clear prefix so the user knows it's the AI agent
        final_comment = f"**🤖 Posted by Agent Orchestrator:**\n\n{agent_comment}"
        
        try:
            comment_url = gh_client.post_comment(task['issue_node_id'], final_comment)
            if comment_url:
                print(f"[*] Comment posted successfully: {comment_url}")
            else:
                print("[!] Comment posted, but URL not returned.")
        except Exception as e:
            print(f"[!] Failed to post comment: {e}")
            sys.exit(1)
    else:
        print("[*] No comment generated by the agent.")
    
    print(f"[*] Updating task status on GitHub to '{next_status}'...")
    try:
        gh_client.update_item_status(task['project_item_id'], next_status)
        print(f"[*] Task status successfully updated. Orchestration complete.")
    except Exception as e:
        print(f"[!] Failed to update status to {next_status}: {e}")
        sys.exit(1)

def main():
    args = parse_arguments()
    target_status = args.status
    repo_path = os.path.abspath(args.repo_path)
    interval = args.interval

    if not os.path.isdir(os.path.join(repo_path, ".git")):
        print(f"[!] Error: The path '{repo_path}' is not a valid git repository.", file=sys.stderr)
        sys.exit(1)

    print(f"[*] Starting GitHub Agent Orchestrator")
    if target_status:
        print(f"[*] Mode: Single Run")
        print(f"[*] Target Status: {target_status}")
    else:
        print(f"[*] Mode: Continuous Daemon")
        print(f"[*] Polling Interval: {interval} seconds")
    print(f"[*] Target Repository: {repo_path}")

    token, project_id, status_field_id = check_environment_variables()

    print("[*] Connecting to GitHub Projects...")
    try:
        gh_client = GitHubClient(token, project_id, status_field_id)
    except Exception as e:
        print(f"[!] Failed to initialize GitHub Client: {e}")
        sys.exit(1)

    if target_status:
        print(f"[*] Searching for a task with status: '{target_status}'...")
        task = gh_client.get_first_item_by_status(target_status)

        if not task:
            print(f"[*] No tasks found with status '{target_status}'. Exiting.")
            sys.exit(0)

        print(f"[*] Found Task: {task['issue_title']} (Issue #{task['issue_number']})")
        print(f"[*] URL: {task['issue_url']}")

        run_orchestration_loop(gh_client, task, target_status, repo_path)
    else:
        print("[*] Starting polling loop (Round Robin)...")
        try:
            status_index = 0
            empty_cycles = 0
            
            while True:
                status = VALID_STATUSES[status_index]
                task = gh_client.get_first_item_by_status(status)
                
                if task:
                    print(f"\n[*] Found Task in '{status}': {task['issue_title']} (Issue #{task['issue_number']})")
                    print(f"[*] URL: {task['issue_url']}")
                    run_orchestration_loop(gh_client, task, status, repo_path)
                    empty_cycles = 0  # Reset empty cycles since we did work
                else:
                    empty_cycles += 1
                
                # Always move to the next status in the list
                status_index = (status_index + 1) % len(VALID_STATUSES)
                
                # If we've checked every single status and found nothing, sleep
                if empty_cycles >= len(VALID_STATUSES):
                    print(f"[*] No actionable tasks found. Sleeping for {interval} seconds...    ", end='\r')
                    time.sleep(interval)
                    empty_cycles = 0 # Reset after sleeping so we don't sleep after every single check
                    
        except KeyboardInterrupt:
            print("\n[*] Daemon mode stopped by user. Exiting.")
            sys.exit(0)

if __name__ == "__main__":
    main()